# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1323bdc151f02af492d2981af930a59d031ee9a1376cdd42597acf1c04a14f25b2d1bb77aaa7fedce0c4059dc3e33cafe1b90684d74620ba3043817d6f763f5a

test:
  secret_key_base: 7a00f15f5e802c5a82e51239dfdd00ce6da5ca44cd6ae1ecfba46696d410c6b99aa4a0d561e7014d1d205495056dbf50417ad46402947aa502e0dd342e7dcde7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
